src/polar_rover/models.py
from flask_login import UserMixin

from polar_rover import db, login_manager


@login_manager.user_loader
def load_user(user_id):
    return Session.query.get(int(user_id))


class Session(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    # One (session) to many (datapoints) relationship
    data = db.relationship('Data', lazy=True)


class Data(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.String(20))
    probe_temp = db.Column(db.Integer)
    bme_temp = db.Column(db.Integer)
    bme_humidity = db.Column(db.Integer)
    bme_alt = db.Column(db.Integer)
    bme_air_pressure = db.Column(db.Integer)

src/polar_rover/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from polar_rover.config import Config


db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'sessions.login'
login_manager.login_message_category = 'info'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    from polar_rover.sessions.routes import sessions
    from polar_rover.main.routes import main
    app.register_blueprint(sessions)
    app.register_blueprint(main)

    return app

src/polar_rover/main/routes.py
import csv

from flask import Blueprint, Response, abort, jsonify, render_template, request
from polar_rover.main.utils import CSV_STREAM, KEY, Output

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home() -> Response:
    """Home page."""
    return render_template('home.html')


@main.route('/about')
def about() -> Response:
    """About page."""
    return render_template('about.html', title='About')


@main.route('/instructions')
def instructions() -> Response:
    """Instructions page."""
    return render_template('instructions.html', title='Instructions')


@main.route('/data')
def get_data():
    """
    Read the data from the cvs file.
    
    Returns 
        data_json (json) : a json containing the information of the file
    """
    times = []
    probe_temps = []
    bme_temps = []
    bme_humidity = []
    bme_altitudes = []
    bme_airpress = []
    with open(CSV_STREAM) as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        line_count = 0
        for row in csv_reader:
            if line_count != 0:
                times.append(row[0])
                probe_temps.append(float(row[1]))
                bme_temps.append(float(row[2]))
                bme_humidity.append(float(row[3]))
                bme_altitudes.append(float(row[4]))
                bme_airpress.append(float(row[5]))
            line_count += 1
    data = {'timestamps' : times, 'probeTemp' : probe_temps, 'bmeTemp' : bme_temps,
            'bmeHumid' : bme_humidity, 'bmeAlt': bme_altitudes, 'bmeAir': bme_airpress}
    data_json = jsonify({'data' : data})
    return data_json

@main.route('/update', methods=['POST'])
def update():
    r = request.form
    # Validate the user
    if r.get('key'):
        if not user_validation(r.get('key')):
            print("Couldn't validate user")
            abort(403)
    if r.get('probeTemp'):
        probeTemp = r.get('probeTemp')
    else:
        abort(404)
    if r.get('bmeTemp'):
        bmeTemp = r.get('bmeTemp')
    else:
        abort(404)
    if r.get('bmeHumid'):
        bmeHumid = r.get('bmeHumid')
    else:
        abort(404)
    if r.get('bmeAlt'):
        bmeAlt = r.get('bmeAlt')
    else:
        abort(404)
    if r.get('bmeAir'):
        bmeAir = r.get('bmeAir')
    else:
        abort(404)
    timestamp = datetime.now().strftime("%d/%m/%Y %H:%M:%S") # get the current time of the data being pushed

    with open(CSV_STREAM, 'a') as csv_file:
        csv_file.write("{}, {}, {}, {}, {}, {}\n".format(timestamp, probeTemp, bmeTemp, bmeHumid, bmeAlt, bmeAir))
    
    return Output("Successfully updated the data.", 201)


@main.route('/reset', methods=['POST'])
def reset() -> Output:
    """Reset database."""
    if request.form.get('key') != KEY:
        abort(403)
    with open(CSV_STREAM, 'w') as csv_file:
        csv_file.write('Timestamp,Probe Temperature [C],BME Temperature [C],BME Humidity [%],BME Altitude [m],BME Air Pressure [hPA]\n')
    return Output('Successfully reset the data.', 201)

src/polar_rover/routes.py
import importlib.resources as pkg_resources
from dataclasses import dataclass

import pandas as pd
from flask import Response, abort, jsonify, render_template, request

import polar_rover


@dataclass(frozen=True)
class Output():
    """Inmutable class for containing return message and code."""
    message: str
    return_code: int

# CSV file is imported from package route as file stream
CSV_STREAM = pkg_resources.open_text(polar_rover, 'data.csv')
KEY = '6,wD-Ak]^wzWe@G'  # expected key for verification

@polar_rover.app.route('/')
@polar_rover.app.route('/home')
def home():
    """Home page."""
    return render_template('home.html')


@polar_rover.app.route('/about')
def about():
    """About page."""
    return render_template('about.html', title='About')


@polar_rover.app.route('/instructions')
def instructions():
    """Instructions page."""
    return render_template('instructions.html', title='Instructions')

@polar_rover.app.route('/register')
def register():

@polar_rover.app.route('/data')
def data() -> Response:
    """Read the data from the cvs file.

    Returns
        data_json (Response): json containing the information of the file
    """
    return jsonify({'data': pd.read_csv(CSV_STREAM).to_dict()})


@polar_rover.app.route('/update', methods=['POST'])
def update() -> Output:
    """Update csv values from request."""
    values = {}
    for field in 'key', 'probeTemp', 'bmeTemp', 'bmeHumid', 'bmeAlt', 'bmeAir':
        try:
            values[field] = request.form[field]
        except:
            abort(404)
    with open(CSV_STREAM, 'a') as csv_file:
        csv_file.write(', '.join(values.items()))
    return Output('Successfully reset the data.', 201)


@polar_rover.app.route('/reset', methods=['POST'])
def reset() -> Output:
    """Reset database."""
    if request.form.get('key') != KEY:
        abort(403)
    with open(CSV_STREAM, 'w') as csv_file:
        csv_file.write('Timestamp,Probe Temperature [C],BME Temperature [C],BME Humidity [%],BME Altitude [m],BME Air Pressure [hPA]\n')
    return Output('Successfully reset the data.', 201)

src/polar_rover/templates/home.html
{% extends "layout.html" %}
{% block content %}

<canvas id="myChart" width=0 height=0></canvas>
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Select Data
    </button>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item">Probe Temperature</a>
        <a class="dropdown-item">BME Temperature</a>
        <a class="dropdown-item">Humidity</a>
        <a class="dropdown-item">Air Pressures</a>
        <a class="dropdown-item">Altitude</a>
    </div>
</div>

{% endblock content %}

src/polar_rover/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="static/css/main.css">

    {% if title %}
        <title>Polar Rover - {{ title }}</title>
    {% else %}
        <title>Polar Rover Utility Server</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Polar Rover</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Visualizer</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('sessions.logout') }}">Logout</a>
                <!-- <a class="nav-item nav-link" href="{{ url_for('sessions.account') }}">Account</a> -->
                {% else %}
                <a class="nav-item nav-link" href="{{ url_for('sessions.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('sessions.register') }}">Register</a>
                {% endif %}
                <a class="nav-item nav-link" href="https://github.com/chinarjoshi/polar-rover">View Repository</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>How to Use</h3>
            <p class='text-muted'>Tutorial and Instructions
              <ul class="list-group">
                  <li class="list-group-item list-group-item-light" href="{{ url_for('main.instructions') }}">ESP32</li>
                  <li class="list-group-item list-group-item-light" href="{{ url_for('main.instructions') }}">Connecting to server</li>
                  <li class="list-group-item list-group-item-light" href="{{ url_for('main.instructions') }}">Understanding the data</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Javascript libraries -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src ="static/js/charts.js"></script>
</body>
</html>